CREATE TABLE CALCULO_SUELDO(FECHA_CALCULO DATE NOT NULL, SUELDO_MENSUAL NUMERIC(10,2) NOT NULL, SUELDO_QUINCENAL NUMERIC(10,2) NOT NULL, IVA NUMERIC AS (SUELDO_MENSUAL * (.16)) VIRTUAL);

INSERT INTO CALCULO_SUELDO(FECHA_CALCULO, SUELDO_MENSUAL, SUELDO_QUINCENAL) VALUES (TO_DATE('01/01/2010 12:00:00', 'dd/mm/yyyy hh24:mi:ss'), 3000, 1500);

/* se observa que el iva se calcula a partir del sueldo mensual
