CREATE TABLE PUESTO ( PUESTO_ID NUMERIC(2,0) NOT NULL PRIMARY KEY, NIVEL CHAR(1) NOT NULL, CLAVE VARCHAR(3) NOT NULL, SUELDO NUMERIC(8,2) NOT NULL CHECK (SUELDO <= 100000));

ALTER TABLE PUESTO ADD CONSTRAINT CLEARED CHECK (NIVEL='a' OR NIVEL='b'OR NIVEL='c') ;

INSERT INTO PUESTO(PUESTO_ID, NIVEL, CLAVE, SUELDO) VALUES (2, 'X', 'ab', 3000);
INSERT INTO PUESTO(PUESTO_ID, NIVEL, CLAVE, SUELDO) VALUES (2, 'a', 'cd', 300000);
INSERT INTO PUESTO(PUESTO_ID, NIVEL, CLAVE, SUELDO) VALUES (2, 'a', 'cd', 300);
