/*
SELECT CURSO.CURSO_ID,CURSO.CUPO_MAXIMO,PROFESOR.NOMBRE,HORARIO.DIA_SEMANA,HORARIO.HORA_INICIO,HORARIO.HORA_FIN
FROM (((((CURSO 
INNER JOIN PROFESOR ON PROFESOR.PROFESOR_ID=CURSO.PROFESOR_ID)
INNER JOIN CURSO_HORARIO ON CURSO.CURSO_ID=CURSO_HORARIO.CURSO_ID)
INNER JOIN SEMESTRE ON SEMESTRE.SEMESTRE_ID=CURSO.SEMESTRE_ID)
INNER JOIN HORARIO ON CURSO_HORARIO.HORARIO_ID=HORARIO.HORARIO_ID)
INNER JOIN ASIGNATURA ON ASIGNATURA.ASIGNATURA_ID=CURSO.ASIGNATURA_ID)
WHERE (SEMESTRE.ANIO=2008 AND SEMESTRE.PERIODO=1 AND ASIGNATURA.NOMBRE='CALCULO 2');

SELECT CURSO.CURSO_ID,CURSO.CLAVE_GRUPO,ASIGNATURA.NOMBRE
FROM ((ASIGNATURA
INNER JOIN CURSO ON ASIGNATURA.ASIGNATURA_ID=CURSO.ASIGNATURA_ID)
INNER JOIN ESTUDIANTE_INSCRITO ON CURSO.CURSO_ID=ESTUDIANTE_INSCRITO.CURSO_ID)
WHERE (ESTUDIANTE_INSCRITO.CALIFICACION IS NULL);

SELECT *
FROM PROFESOR
NATURAL JOIN  CURSO
WHERE PROFESOR.APELLIDO_PATERNO='KRAUCE';

@EJERCICIOSBASES.sql
*/

SELECT PROFESOR.PROFESOR_ID, PROFESOR.APELLIDO_PATERNO, PROFESOR.APELLIDO_MATERNO, CURSO.CLAVE_GRUPO 
FROM ((PROFESOR
INNER JOIN CURSO ON PROFESOR.PROFESOR_ID=CURSO.PROFESOR_ID)
INNER JOIN SEMESTRE ON CURSO.SEMESTRE_ID=SEMESTRE.SEMESTE_ID)
WHERE SEMESTRE.SEMESTRE_ID=1;

