/*SELECT ESTUDIANTE.NOMBRE,ESTUDIANTE.APELLIDO_PATERNO, ESTUDIANTE.APELLIDO_MATERNO,ASIGNATURA.NOMBRE,ESTUDIANTE_INSCRITO.CALIFICACION 
FROM (((ESTUDIANTE 
INNER JOIN ESTUDIANTE_INSCRITO ON ESTUDIANTE.ESTUDIANTE_ID=ESTUDIANTE_INSCRITO.ESTUDIANTE_ID) 
INNER JOIN CURSO ON CURSO.CURSO_ID=ESTUDIANTE_INSCRITO.CURSO_ID) 
INNER JOIN ASIGNATURA ON ASIGNATURA.ASIGNATURA_ID=CURSO.ASIGNATURA_ID) 
WHERE ESTUDIANTE.NOMBRE='JUAN' 
AND ESTUDIANTE.APELLIDO_PATERNO='JUAREZ' 
AND ESTUDIANTE.APELLIDO_MATERNO='MENDOZA';
*/
SELECT CURSO_ID,CUPO_MAXIMO,PROFESOR.NOMBRE,DIA_SEMANA,HORA_INICIO,HORA_FIN
FROM ((CURSO 
INNER JOIN PROFESOR ON PROFESOR.PROFESOR_ID=CURSO.PROFESOR_ID)
INNER JOIN CURSO_HORARIO ON CURSO.CURSO_ID=CURSO_HORARIO.CURSO_ID)
INNER JOIN SEMESTRE ON SEMESTRE.SEMESTRE_ID=CURSO.CURSO_ID)
WHERE SEMESTRE.ANIO=TO_DATE('2008','YYYY');

