SELECT ASIGNATURA_ID, NOMBRE, PLAN_ESTUDIOS_ID, CREDITOS 
FROM ASIGNATURA 
WHERE PLAN_ESTUDIOS_ID IN (1, 2) 
MINUS 
SELECT ASIGNATURA_ID, NOMBRE, PLAN_ESTUDIOS_ID, CREDITOS 
FROM ASIGNATURA 
WHERE CREDITOS>=9;
