SELECT NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,NULL AS NUM_EXAMEN,NULL AS CALIFICACION,NULL AS ASIGNATURA_ID 
FROM ESTUDIANTE 
WHERE ESTUDIANTE_ID=21 
UNION ALL 
SELECT NULL,NULL,NULL,NUM_EXAMEN,CALIFICACION,ASIGNATURA_ID 
FROM ESTUDIANTE_EXTRAORDINARIO 
WHERE ESTUDIANTE_ID=21;

SELECT ESTUDIANTE.NOMBRE, ESTUDIANTE.APELLIDO_PATERNO, ESTUDIANTE.APELLIDO_MATERNO, ESTUDIANTE_EXTRAORDINARIO.NUM_EXAMEN, ESTUDIANTE_EXTRAORDINARIO.CALIFICACION, ESTUDIANTE_EXTRAORDINARIO.ASIGNATURA_ID 
FROM ESTUDIANTE 
INNER JOIN ESTUDIANTE_EXTRAORDINARIO ON ESTUDIANTE.ESTUDIANTE_ID=ESTUDIANTE_EXTRAORDINARIO.ESTUDIANTE_ID 
WHERE ESTUDIANTE.ESTUDIANTE_ID=21;
