SELECT ESTUDIANTE.NOMBRE,ESTUDIANTE.APELLIDO_PATERNO, ESTUDIANTE.APELLIDO_MATERNO,ASIGNATURA.NOMBRE,ESTUDIANTE_INSCRITO.CALIFICACION 
FROM (((ESTUDIANTE 
INNER JOIN ESTUDIANTE_INSCRITO ON ESTUDIANTE.ESTUDIANTE_ID=ESTUDIANTE_INSCRITO.ESTUDIANTE_ID) 
INNER JOIN CURSO ON CURSO.CURSO_ID=ESTUDIANTE_INSCRITO.CURSO_ID) 
INNER JOIN ASIGNATURA ON ASIGNATURA.ASIGNATURA_ID=CURSO.ASIGNATURA_ID) 
WHERE ESTUDIANTE.NOMBRE='JUAN' 
AND ESTUDIANTE.APELLIDO_PATERNO='JUAREZ' 
AND ESTUDIANTE.APELLIDO_MATERNO='MENDOZA';
