SELECT PROFESOR.NOMBRE,PROFESOR.RFC,PROFESOR.FECHA_NACIMIENTO FROM PROFESOR WHERE((FECHA_NACIMIENTO>TO_DATE('1949','YYYY')) AND (FECHA_NACIMIENTO<TO_DATE('1956','YYYY'))) OR ((FECHA_NACIMIENTO>TO_DATE('1959','YYYY')) AND (FECHA_NACIMIENTO<TO_DATE('1966','YYYY')));

SELECT PROFESOR.NOMBRE,PROFESOR.RFC,PROFESOR.FECHA_NACIMIENTO FROM PROFESOR WHERE(FECHA_NACIMIENTO>TO_DATE('1949','YYYY')) INTERSECT SELECT PROFESOR.NOMBRE,PROFESOR.RFC,PROFESOR.FECHA_NACIMIENTO FROM PROFESOR WHERE (FECHA_NACIMIENTO<TO_DATE('1956','YYYY')) UNION SELECT PROFESOR.NOMBRE,PROFESOR.RFC,PROFESOR.FECHA_NACIMIENTO FROM PROFESOR WHERE (FECHA_NACIMIENTO>TO_DATE('1959','YYYY')) INTERSECT SELECT PROFESOR.NOMBRE,PROFESOR.RFC,PROFESOR.FECHA_NACIMIENTO FROM PROFESOR WHERE (FECHA_NACIMIENTO<TO_DATE('1966','YYYY'));

/*CONDICIONES DE PROFESOR : MAYOR A 1970, JUAN O LUISA O LENIN, AP INCIA CON LETRA R */

SELECT * FROM PROFESOR WHERE (FECHA_NACIMIENTO>TO_DATE('1970','YYYY')) INTERSECT SELECT * FROM PROFESOR WHERE NOMBRE IN ('LUISA','LENIN','JUAN') INTERSECT SELECT * FROM PROFESOR WHERE APELLIDO_PATERNO LIKE 'R%';

SELECT * FROM CURSO WHERE CUPO_MAXIMO=30 MINUS (SELECT * FROM CURSO WHERE CLAVE_GRUPO='001' );
